### PR TITLE
enable ssl for http conn

### PR DESCRIPTION
**Pull request by nathanhruby**
This simply adds support for HTTPS when requested by the URL.

### CODE REVIEW

**Comment by nathanhruby** [comment]
Hi,

It looks like there are two classes of test failures going on:
- dependent gems require ruby 2.1, thus breaking ruby 1.9 and 2.0 tests
- `test_emit_json(HTTPOutputTest)` fails because it's being processed in UTF-8 instead of ASCII when read to JSON (IIRC I think is a defaults change in later rubies)

Any thoughts on what should be done here?

-n

**Comment by nathanhruby** [comment]
I updated this PR to drop old ruby support and fix tests.  Is it possible to get a review/merge?

**Comment by ento** [comment]
Thanks! I'll try to get around to it this weekend.

**Comment by nathanhruby** [comment]
Awesome, thank you!

**Comment by ento** [comment]
Released as v0.2.0

**Comment by nathanhruby** [comment]
Wow, thank you very much!

**Pull request merged**
